apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-scaler-deployment
  namespace: ${{ vars.SERVICE_ACCOUNT_NAMESPACE }}
  labels:
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-scaler
  template:
    metadata:
      labels:
        app: aks-scaler
    spec:
      serviceAccountName: ${{vars.SERVICE_ACCOUNT_NAMESPACE}}
      containers:
        - image: ${{ vars.CONTAINER_REGISTRY }}.azurecr.io/aks-skaler:latest
          name: oidc
          env:
          - name: SUBSCRIPTION
            valueFrom:
              secretKeyRef:
                name: subscription-secret
                key: subscription
          - name: NODE_POOLS_AMOUNT
            valueFrom:
              secretKeyRef:
                name: node-pools-amount-secret
                key: node-pools-amount
          - name: RESOURCE_GROUP
            valueFrom:
              secretKeyRef:
                name: resource-group-secret
                key: resource-group
          - name: LOCATION
            valueFrom:
              secretKeyRef:
                name: location-secret
                key: location
          - name: CLUSTER_NAME
            valueFrom:
              secretKeyRef:
                name: cluster-name-secret
                key: cluster-name
      nodeSelector:
        kubernetes.io/os: linux
