apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-scaler-deployment
  namespace: ${{ vars.SERVICE_ACCOUNT_NAMESPACE }}
  labels:
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-scaler
  template:
    metadata:
      labels:
        app: aks-scaler
    spec:
      serviceAccountName: default # HACK: should be replaced in helm values files ${{vars.SERVICE_ACCOUNT_NAMESPACE}}
      containers:
        - image: acr4aksregistry.azurecr.io/aks-skaler:latest # HACK: should be replaced in helm values files ${{vars.CONTAINER_REGISTRY}}
          name: oidc
          env:
          - name: SUBSCRIPTION
            valueFrom:
              secretKeyRef:
                name: subscription-secret
                key: subscription
          - name: NODE_POOLS_AMOUNT
            valueFrom:
              configMapKeyRef:
                name: aks-scaler-configmap
                key: node-pools-amount
          - name: RESOURCE_GROUP
            valueFrom:
              configMapKeyRef:
                name: aks-scaler-configmap
                key: resource-group
          - name: LOCATION
            valueFrom:
              configMapKeyRef:
                name: aks-scaler-configmap
                key: location
          - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: aks-scaler-configmap
                key: cluster-name
      nodeSelector:
        kubernetes.io/os: linux