apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-scaler-deployment
  namespace: ${{ vars.SERVICE_ACCOUNT_NAMESPACE }}
  labels:
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-scaler
  template:
    metadata:
      labels:
        app: aks-scaler
    spec:
      serviceAccountName: ${{vars.SERVICE_ACCOUNT_NAMESPACE}}
      containers:
        - image: ${{ vars.CONTAINER_REGISTRY }}.azurecr.io/aks-skaler:latest
          name: oidc
          env:
          - name: SUBSCRIPTION
            value: ${{ secrets.SUBSCRIPTION }}
          - name: NODE_POOLS_AMOUNT
            value: ${{ vars.NODE_POOLS_AMOUNT }}
          - name: RESOURCE_GROUP
            value: ${{ vars.RESOURCE_GROUP }}
          - name: LOCATION
            value: ${{ vars.LOCATION }}
          - name: CLUSTER_NAME
            value: ${{ vars.CLUSTER_NAME }}
      nodeSelector:
        kubernetes.io/os: linux
