name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  checkoutAndBuildImage:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    steps:
        - uses: actions/checkout@v3
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: acr login
          run: az acr login --name ${{ vars.CONTAINER_REGISTRY }} --expose-token
        - name: Build and push checkout image to ACR (${{ vars.CONTAINER_REGISTRY }})
          run: az acr build --image aks-skaler:latest --registry ${{ vars.CONTAINER_REGISTRY }} --file Dockerfile .

  deployToAKS:
    needs: checkoutAndBuildImage
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    steps:
        - uses: actions/checkout@v3
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: acr login
          run: az acr login --name ${{ vars.CONTAINER_REGISTRY }} --expose-token

        # Use kubelogin to configure your kubeconfig for Azure auth
        - name: Set up kubelogin for non-interactive login
          uses: azure/use-kubelogin@v1
          with:
            kubelogin-version: 'v0.0.25'

        # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
        - name: Get K8s context
          uses: azure/aks-set-context@v3
          with:
            resource-group: ${{ vars.RESOURCE_GROUP }}
            cluster-name: ${{ vars.CLUSTER_NAME }}
            admin: 'false'
            use-kubelogin: 'true'

        - uses: azure/setup-kubectl@v3
          with:
              version: 'latest' # default is latest stable
          id: install
        - name: create subscription-secret
          run: |
            if kubectl get secret subscription-secret -n ${{ vars.SERVICE_ACCOUNT_NAMESPACE }} >/dev/null 2>&1; then
              echo "Secret subscription-secret already exists"
            else
              kubectl create secret generic subscription-secret --from-literal=subscription='${{ secrets.SUBSCRIPTION }}' --namespace=${{ vars.SERVICE_ACCOUNT_NAMESPACE }}
            fi
        - name: create aks-scaler-configmap
          run: |
            kubectl create configmap aks-scaler-configmap \
              --from-literal=resource-group='${{ vars.RESOURCE_GROUP }}' \
              --from-literal=location='${{ vars.LOCATION }}' \
              --from-literal=cluster-name='${{ vars.CLUSTER_NAME }}' \
              --from-literal=node-pools-amount='${{ vars.NODE_POOLS_AMOUNT }}' \
              --namespace=${{ vars.SERVICE_ACCOUNT_NAMESPACE }}

        # Deploys application based on given manifest file
        - name: Deploys application
          uses: Azure/k8s-deploy@v4
          with:
            action: deploy
            manifests: ${{ vars.DEPLOYMENT_MANIFEST_PATH }}
            images: |
              ${{ vars.CONTAINER_REGISTRY }}.azurecr.io/${{ vars.CONTAINER_NAME }}:latest
